[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts",
    "@solmate/tokens/=lib/solmate/src/tokens",
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 10

[etherscan]
polygon-amoy = { key = "${AMOY_API_KEY}", url = "https://www.oklink.com/api/explorer/v1/contract/verify/async/api/polygonAmoy" }

[[profile.default.contract]]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
